### ISSUE TITLE
Send Mail Function

### ISSUE THREAD

**Issue by TRUYEN-PRD** [TRUYEN-PRD/PTSResearch#2]
Kiểm tra và chỉnh đưa ra giải pháp cho hệ thống hiện tại gửi được email.

**Comment by thosuperman** [comment]
Hiện tại hệ thống test sử dụng gmail nên cần thay đổi một vài thông số về cấu hình như sau:

SMTP host: **ssl://smtp.googlemail.com** (bắt buộc phải có ssl:// phía trước)
SMTP port: 465

Ngoài ra còn có thể gặp lỗi block access từ phía google (less secure apps) nên cần turn on Access for less secure apps
https://www.google.com/settings/security/lesssecureapps
