### ISSUE TITLE
Kiểm tra đơn hàng bằng BTC

### ISSUE THREAD

**Issue by TRUYEN-PRD** [TRUYEN-PRD/PTSResearch#3]
Kiểm tra và lý giải tại sao đơn đặt hàng bằng BTC không hiện lên trên màn hình chờ nhận tiền. (入金待ち一覧)

**Comment by thosuperman** [comment]
- Hiện tại em kiểm tra thấy crontab chưa được set nên đơn hàng không hiển thị được, em đã thử chạy manual thì đơn hàng đã hiển thị.

**Comment by thosuperman** [comment]
Trong Operator -> syncBlock, function getApi không hoạt động được trên testnet ( http://test-insight.bitpay.com/api ) nên không kiểm tra được transaction. Em đã sửa lại như sau:

`$ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
            //curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-type: application/json'));
            curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36");

            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
            curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
            curl_setopt($ch, CURLOPT_HEADER, false);

            $output = curl_exec($ch);
            curl_close($ch);
            return $output;`

**Comment by thosuperman** [comment]
Ubuntu 16.04 mysql default đang phát sinh lỗi ở **Interbank/getRateFromDB**

> this is incompatible with sql_mode=only_full_group_by

Khắc phục bằng cách:

> set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

> set session sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

Reference: http://stackoverflow.com/questions/34115174/error-related-to-only-full-group-by-when-executing-a-query-in-mysql
